apiVersion: v1
kind: Service
metadata:
  name: {{ include "gameoflife.fullname" . }}
  labels:
    {{- include "gameoflife.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: gameoflife
  selector:
    {{- include "gameoflife.selectorLabels" . | nindent 4 }}
